---
title: "Week-5"
author: "Viraj Sapre, Sinchana Mysore Eshwar, Kartik Nagarajan"
date: "March 8, 2019"
output:
  word_document: default
  html_document: default
  pdf_document: default
---
```{r}
#Loading the libraries
library(ggplot2)
library(ggthemes)
library(dplyr)
library(gridExtra)
library(corrplot)
library(GGally)
library(data.table)
library(scales)
library(MVA)
library(Rmisc)

```

```{r}
# loading the dataset
train <- read.csv("~/MS SEM 2/Multivariate Analysis - Raunak Parikh/MVA Grp Project/train.csv")
View(train)
```

UNDERSTANDING THE DATA

```{r}
dim(training) # checking the dimensions
```

```{r}
str(training)# checking the structure of dataset
```

```{r}
summary(training)# checking the summary of dataset
```

Checking for MISSING VALUES

```{r}
#Missing data
sum(is.na(training)/(nrow(training)*nrow(training)))# printing percentage of missing data
unique(nrow(training)) # printing all the unique values

colSums(sapply(training,is.na))# prinitng number of missing values in each column 

```

```{r}
library(Amelia)
missmap(training, main ="Missing values vs observed")
```


```{r}
# creating dataframe of categorical and numerical variables
catvar <- c('MSZoning','Street', 'Neighborhood', 'LandContour','BldgType', 'LandSlope', 'RoofStyle',
             'HouseStyle','CentralAir','PavedDrive','SaleCondition','OverallCond' )
numvar<-c('LotArea','TotalBsmtSF','GrLivArea','BedroomAbvGr','GarageCars','GarageArea','OpenPorchSF','EnclosedPorch','WoodDeckSF','PoolArea')

```

```{r}
unique(nrow(training$SalePrice))
```

Removing columns with NA values 

```{r}
training$Alley = NULL 
training$LotFrontage = NULL
training$FireplaceQu = NULL
training$Fence = NULL
training$PoolQC = NULL 
training$MiscFeature = NULL 
training$BsmtQual = NULL 
training$BsmtCond = NULL 
training$BsmtExposure = NULL 
training$BsmtFinType1 = NULL 
training$BsmtFinType2 = NULL
training$GarageType = NULL
training$GarageYrBlt = NULL
training$MasVnrType = NULL 
training$MasVnrArea = NULL 
training$GarageQual = NULL 
training$GarageFinish = NULL 
training$GarageCond = NULL
training$Id=NULL

```

```{r}
training[!complete.cases(training),]
```


```{r}
head(training)
```

```{r}
#Missing data
sum(is.na(training)/(nrow(training)*nrow(training)))# printing percentage of missing data
unique(nrow(training)) # printing all the unique values

colSums(sapply(training,is.na))# prinitng number of missing values in each column 

```


```{r}
attach(training)  
catdf<-training[,catvar]
numdf<-training[,numvar]

```

VISUALIZING THE DATA


```{r}
ggplot(training, aes(x = SaleCondition, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()

```

```{r}
pairs(~SalePrice+LotArea+TotalBsmtSF+GrLivArea, data=training,col=c('red','blue','green'))

```

```{r}
as.factor(training$SalePrice)
hist(training$SalePrice / 1000, xlab = "Saleprice in thousands")
library(moments)
skewness(SalePrice)
```

```{r}
boxplot(training$SalePrice/ 1000, main = "Saleprice")
```


```{r}
par(mfrow=c(2,4))
hist(training$LotArea,xlab="Lot Area", main="Lot Area")
hist(training$TotalBsmtSF, xlab="Basement Area", main="Basement Area")
hist(training$BedroomAbvGr, xlab="No of Bedrooms", main="No of Bedrooms")
hist(training$GrLivArea, xlab="Living Area",main="Living Area")
hist(training$GarageCars, xlab="No. of Cars",main="No. of Cars")
hist(training$GarageArea, xlab="Garage Area",main="Garage Area")
hist(training$PoolArea, xlab="Pool Area",main="Pool Area")
hist(training$OpenPorchSF, xlab="Open Porch Area",main="Open Porch Area")
```

```{r}
ggplot(training, aes(x = Neighborhood, y = SalePrice)) +
  geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()
```
```{r}
ggplot(training, aes(x = MSZoning, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()


ggplot(training, aes(x = Street, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()

ggplot(training, aes(x = LandContour, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()

ggplot(training, aes(x = BldgType, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()

ggplot(training, aes(x = PavedDrive, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()


ggplot(training, aes(x = as.factor(OverallCond), y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()
```

```{r}
ggplot(training, aes(x = LandSlope, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()

ggplot(training, aes(x = RoofStyle, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()

ggplot(training, aes(x = HouseStyle, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()

ggplot(training, aes(x = CentralAir, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()


```

```{r}
library(PerformanceAnalytics)
my_data <- training[, c('SalePrice','LotArea','TotalBsmtSF','GrLivArea','GarageArea')]

chart.Correlation(my_data, histogram=TRUE, pch=19)
```

```{r}
my_data <- training[, c('SalePrice','BedroomAbvGr','TotRmsAbvGrd','GarageCars','OpenPorchSF','EnclosedPorch','WoodDeckSF')]

chart.Correlation(my_data, histogram=TRUE, pch=19)
```

```{r}
library(forecast)
linear <- lm(SalePrice~., data=training, metric="RMSE", maximize=FALSE)
summary(linear)
accuracy(linear)
plot(linear)
```


```{r}
library(car)
x <- c( BedroomAbvGr, LotArea, PoolArea, TotalBsmtSF, TotRmsAbvGrd)
qqPlot(x , main="QQ Plot")

```

```{r}
library(ggpubr)
t.test(SalePrice, x, data = training)
```

```{r}
library(Hmisc)
describe(training)
```


```{r}
boxplot(training$SalePrice / 1000 )
```


```{r}
cat_var <- names(training)[which(sapply(training, is.factor))]
cat_var
```
```{r}
num_var <- c('SalePrice','LotArea','TotalBsmtSF','GrLivArea','BsmtFinSF1','BsmtFinSF2','X1stFlrSF','X2ndFlrSF','GarageArea','WoodDeckSF','OpenPorchSF')
training_pca<-training[,num_var]
training_pca<-training_pca[,-1]
training_pca

```



```{r}
library(stats)
library(factoextra)
pca <- prcomp(training_pca, scale. = T, center = T)
pca
```

```{r}
eigenvalues <- get_eigenvalue(pca)
eigenvalues <- pca$sdev^2
sum(eigenvalues)
```

```{r}
plot(pca)
```

```{r}
summary(pca)
```
```{r}
head(pca$x)

```


```{r}
library(factoextra)
fviz_screeplot(pca, ncp = 35)
```

```{r}
plot(pca, type = "l", main = "Scree diagram")
plot(eigenvalues, xlab = "Component number", ylab = "Component variance", type = "l", main ="Scree diagram")

```

```{r}
diag(cov(pca$x))
xlim <- range(pca$x[,1])




```

```{r}
plot(pca$x,xlim=xlim,ylim=xlim)




```

```{r}
pca$rotation[,1]
pca$rotation[,2]
pca$rotation[,3]
pca$rotation[,4]
pca$rotation[,5]
```


