---
title: "Week-2"
author: "Viraj Sapre, Sinchana Eshwar, Kartik Nagarajan"
date: "February 15, 2019"
output:
  word_document: default
  html_document: default
---
```{r}
#Loading the libraries
library(ggplot2)
library(ggthemes)
library(dplyr)
library(gridExtra)
library(corrplot)
library(GGally)
library(data.table)
library(scales)
library(MVA)
library(Rmisc)

```

```{r}
# loading the dataset
training <- read.csv("~/MS SEM 2/Multivariate Analysis - Raunak Parikh/MVA Grp Project/train.csv")
View(training)
testing <- read.csv("~/MS SEM 2/Multivariate Analysis - Raunak Parikh/MVA Grp Project/test.csv")
View(testing)

```

UNDERSTANDING THE DATA

```{r}
dim(training) # checking the dimensions
```

```{r}
str(training)# checking the structure of dataset
```

```{r}
summary(training)# checking the summary of dataset
```


```{r}
dim(testing)# checking the dimensions
```

```{r}
str(testing)# checking the structure of dataset
```

```{r}
summary(testing)# checking the summary of dataset
```


```{r}
# combining training and testing datasets
housedata<-bind_rows(training,testing)
View(housedata)
head(housedata) # printing the first 6 rows of the dataset
```

```{r}
dim(housedata) # checking the dimensions of dataset
str(housedata)# checking the structure of dataset

```

```{r}
summary(housedata)# checking the summary of dataset
```

Checking for MISSING VALUES

```{r}
#Missing data
sum(is.na(housedata)/(nrow(housedata)*nrow(housedata)))# printing percentage of missing data
unique(nrow(housedata)) # printing all the unique values

colSums(sapply(housedata,is.na))# prinitng number of missing values in each column 

```

```{r}
library(Amelia)
missmap(training, main ="Missing values vs observed")
```


```{r}
# creating dataframe of categorical and numerical variables
catvar <- c('MSZoning','Street', 'Neighborhood', 'LandContour','BldgType', 'LandSlope', 'RoofStyle',
             'HouseStyle','CentralAir','PavedDrive','SaleCondition','OverallCond' )
numvar<-c('SalePrice','LotArea','TotalBsmtSF','GrLivArea','BedroomAbvGr','TotRmsAbvGrd','GarageCars','GarageArea'
          ,'OpenPorchSF','EnclosedPorch','WoodDeckSF','PoolArea')

```

```{r}
unique(nrow(training$SalePrice))
```


```{r}
attach(housedata)  
catdf<-housedata[,catvar]
numdf<-housedata[,numvar]

```

VISUALIZING THE DATA


```{r}
ggplot(training, aes(x = SaleCondition, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()

```

```{r}
pairs(~SalePrice+LotArea+TotalBsmtSF+GrLivArea, data=training,col=c('red','blue','green'))

```

```{r}
as.factor(training$SalePrice)
hist(training$SalePrice)
```


```{r}
par(mfrow=c(2,4))
hist(training$LotArea,xlab="Lot Area", main="Lot Area")
hist(training$TotalBsmtSF, xlab="Basement Area", main="Basement Area")
hist(training$BedroomAbvGr, xlab="No of Bedrooms", main="No of Bedrooms")
hist(training$GrLivArea, xlab="Living Area",main="Living Area")
hist(training$GarageCars, xlab="No. of Cars",main="No. of Cars")
hist(training$GarageArea, xlab="Garage Area",main="Garage Area")
hist(training$PoolArea, xlab="Pool Area",main="Pool Area")
hist(training$OpenPorchSF, xlab="Open Porch Area",main="Open Porch Area")
```

```{r}
ggplot(training, aes(x = Neighborhood, y = SalePrice)) +
  geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()
```
```{r}
ggplot(training, aes(x = MSZoning, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()


ggplot(training, aes(x = Street, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()

ggplot(training, aes(x = LandContour, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()

ggplot(training, aes(x = BldgType, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()

ggplot(training, aes(x = PavedDrive, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()


ggplot(training, aes(x = as.factor(OverallCond), y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()
```

```{r}
ggplot(training, aes(x = LandSlope, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()

ggplot(training, aes(x = RoofStyle, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()

ggplot(training, aes(x = HouseStyle, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()

ggplot(training, aes(x = CentralAir, y = SalePrice)) +geom_boxplot() +
  geom_hline(aes(yintercept=80), 
             colour='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format()) +
  theme_few()


```

```{r}
library(PerformanceAnalytics)
my_data <- training[, c('SalePrice','LotArea','TotalBsmtSF','GrLivArea','GarageArea')]

chart.Correlation(my_data, histogram=TRUE, pch=19)
```

```{r}
my_data <- training[, c('SalePrice','BedroomAbvGr','TotRmsAbvGrd','GarageCars','OpenPorchSF','EnclosedPorch','WoodDeckSF')]

chart.Correlation(my_data, histogram=TRUE, pch=19)
```

